// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzox4now3S5s0z71Fgb_2MUkJabhGpNlE',
    appId: '1:1054460737302:web:ecec63b1eaeaaebfafc237',
    messagingSenderId: '1054460737302',
    projectId: 'insta-training-5ed15',
    authDomain: 'insta-training-5ed15.firebaseapp.com',
    storageBucket: 'insta-training-5ed15.appspot.com',
    measurementId: 'G-TT7BT5WT4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhWIbVFV4vddmON1oL_LFtfBHIheKMOPs',
    appId: '1:1054460737302:android:f41737080d8ea942afc237',
    messagingSenderId: '1054460737302',
    projectId: 'insta-training-5ed15',
    storageBucket: 'insta-training-5ed15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSphYfsAgIcffyOBvF_3fFcw4z1l3MAhQ',
    appId: '1:1054460737302:ios:7c9ee24d588d3fd5afc237',
    messagingSenderId: '1054460737302',
    projectId: 'insta-training-5ed15',
    storageBucket: 'insta-training-5ed15.appspot.com',
    iosBundleId: 'com.example.instaTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSphYfsAgIcffyOBvF_3fFcw4z1l3MAhQ',
    appId: '1:1054460737302:ios:31dd7632f7b13061afc237',
    messagingSenderId: '1054460737302',
    projectId: 'insta-training-5ed15',
    storageBucket: 'insta-training-5ed15.appspot.com',
    iosBundleId: 'com.example.instaTraining.RunnerTests',
  );
}
